### ISSUE TITLE
I cannot see anything in tensorboard

### ISSUE THREAD

**Issue by OctaM** [kratzert/finetune_alexnet_with_tensorflow#26]
I have successfully trained alexnet for dogs vs cats dataset but when I run tensorboard I can only visualize this page:

![tensorboard](https://user-images.githubusercontent.com/8879730/32456432-3d75a554-c32e-11e7-8927-9a4fdbd4aab7.png)

The rest of the pages are inactive:

![tensorboard2](https://user-images.githubusercontent.com/8879730/32456477-756d6974-c32e-11e7-9ae9-832ac472c335.png)

I have tensorflow 1.3.0, and python 3.6.3 and I am using windows 10. Do you have any idea what can cause the problem?

**Comment by aminullah6264** [comment]
i have the same problem...

**Comment by kratzert** [comment]
I used my code over the weekend and it worked perfectly fine. I think I'm still behind with the TensorFlow version and I use 1.2 or even 1.12. You mind checking if it works with one of the recent versions? I don't know if they changed anything. Also I only have a Linux workstation and can't test Windows so easily so would be good if you can check vs one of the last TensorFlow versions first.

**Comment by OctaM** [comment]
I am using the last version of TensorFlow: 1.3. Also the finetune.py that I'm using is the one in which your wrote: "This script was written for TensorFlow 1.0 and come with a blog post 
you can find here ..." do you think this can be the problem?

**Comment by kratzert** [comment]
I'm not quite sure which version you exactly mean. So please be sure to use the current one. 
- [download current master branch](https://github.com/kratzert/finetune_alexnet_with_tensorflow/archive/master.zip) 
And see if you get the similar error. Actually I don't see why different versions of TF should make a difference but please test against the newest version of this repository.

**Comment by OctaM** [comment]
I just did that and when I try running finetune.py that's the result:

2017-11-08 12:02:47.800938 Start training...
2017-11-08 12:02:47.800938 Open Tensorboard at --logdir E:/Facultate/tensorflow/finetune_alexnet_last_vers/tensorboard
2017-11-08 12:02:47.800938 Epoch number: 1
2017-11-08 12:03:23.639109: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.639645: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.640177: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.648271: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.648670: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.651575: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.651924: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
2017-11-08 12:03:23.652379: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]
Traceback (most recent call last):
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Facultate/Tensorflow/finetune_alexnet_last_vers/finetune.py", line 180, in <module>
    keep_prob: 1.})
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]

Caused by op 'fc8/weights_0', defined at:
  File "E:/Facultate/Tensorflow/finetune_alexnet_last_vers/finetune.py", line 115, in <module>
    tf.summary.histogram(var.name, var)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\summary\summary.py", line 192, in histogram
    tag=tag, values=values, name=scope)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 187, in _histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Users\octam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_43)]]

**Comment by kratzert** [comment]
This is because of a badly chosen learning rate for your data. If you are using dogs-vs-cat data see #23

**Comment by OctaM** [comment]
Gracias mr. kratzert, that solved my problem. I will leave a comment once my training is finished regarding tensorboard.

**Comment by kratzert** [comment]
You know that you can start Tensorboard immediately, when you start training? Don't have to wait for training to finish to see if it's working now. Also, this is exactly what TensorBoard is for: Seeing the development of your network while you train it

**Comment by OctaM** [comment]
Yes I know that and I've tried it, but still I face the same problem as before.

**Comment by kratzert** [comment]
And as asked in my very first answer, did or can you test against e.g. TensorFlow v 1.2 or 1.12?

**Comment by OctaM** [comment]
Now I've tried it with TensorFlow v1.2 and it worked. I know that my next question has nothing to do with this issue, but why are you doing data loading and preprocessing on the cpu?

**Comment by kratzert** [comment]
So it seems to be related to the newer TensorBoard version. But I can't find any changes in the release notes. I'll try it out myself during the next days to see if it's reproducible or if it's coming from something different.

Regarding your second question. Because by this I can use all of the computer resources. Basically its doing both steps in parallel and whenever the GPU has calculated one forward + backward pass for a batch, the next batch is already available in memory and the GPU can already start with the next forward calculation.

**Comment by kratzert** [comment]
I was finally able to test your problem and I can't reproduce it. For me on Ubuntu 16.04 everything works fine in a clean environment with TensorFlow 1.3 and TensorFlow 1.4. Don't know if this is a windows issue and this isn't to easy to test for me, since I only have Linux machines.

For the log:
- In the env of TensorFlow 1.4, Tensorboard starts with the version number 0.4.0.rc3
- In the env of TensorFlow 1.3, Tensorboard starts with the version number 0.1.8

**Comment by kratzert** [comment]
Maybe check this issue. Seems related and they found a solution at the bottom [TF issue 9701](https://github.com/tensorflow/tensorflow/issues/9701)

**Comment by xiexie123** [comment]
guys, is there any chance you open tensorbord within checkpoint_path not filewriter_path...because I made this mistake and get the same page....so...

**Comment by kratzert** [comment]
@OctaM @Aminullah6264 can you please check what @xiexie123 said? Make sure to open tensorboard with log_dir pointing to the correct folder?

**Comment by kratzert** [comment]
closed due to inactivity  and missing response

**Comment by aminullah6264** [comment]
Sorry for late response. i had solve on the same day i got problem.
i just call tensorboard from the same directory and it worked.
