### ISSUE TITLE
error occurs when running jupyter file on my linux server

### ISSUE THREAD

**Issue by graysonliu** [kratzert/finetune_alexnet_with_tensorflow#28]
I want to run file `validate_alexnet_on_imagenet.ipynb` to test the implement of AlexNet. When I run it on my Windows PC, it works well. But when I run it on my Linux server, which is much more powerful than my PC, it's stuck for a while and output a `ResourceExhaustedError`, which I believe occurred in this line:
```
sess.run(tf.global_variables_initializer())
```
Full output is shown below:
```
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1322     try:
-> 1323       return fn(*args)
   1324     except errors.OpError as e:

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1301                                    feed_dict, fetch_list, target_list,
-> 1302                                    status, run_metadata)
   1303 

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive

ResourceExhaustedError: OOM when allocating tensor with shape[4096]
	 [[Node: fc6/biases/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@fc6/biases"], dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc6/biases/Initializer/random_uniform/shape)]]

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-4-eb8e619c57ae> in <module>()
      2 
      3     # Initialize all variables
----> 4     sess.run(tf.global_variables_initializer())
      5 
      6     # Load the pretrained weights into the model

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1119       results = self._do_run(handle, final_targets, final_fetches,
-> 1120                              feed_dict_tensor, options, run_metadata)
   1121     else:
   1122       results = []

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1315     if handle is None:
   1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1317                            options, run_metadata)
   1318     else:
   1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1334         except KeyError:
   1335           pass
-> 1336       raise type(e)(node_def, op, message)
   1337 
   1338   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[4096]
	 [[Node: fc6/biases/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@fc6/biases"], dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc6/biases/Initializer/random_uniform/shape)]]

Caused by op 'fc6/biases/Initializer/random_uniform/RandomUniform', defined at:
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-5d95ec9c311f>", line 9, in <module>
    model = AlexNet(x, keep_prob, 1000, [])
  File "/home1/grayson/finetune_alexnet_with_tensorflow/alexnet.py", line 56, in __init__
    self.create()
  File "/home1/grayson/finetune_alexnet_with_tensorflow/alexnet.py", line 82, in create
    fc6 = fc(flattened, 6*6*256, 4096, name='fc6')
  File "/home1/grayson/finetune_alexnet_with_tensorflow/alexnet.py", line 177, in fc
    biases = tf.get_variable('biases', [num_out], trainable=True)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 805, in _get_single_variable
    constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 779, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py", line 445, in __call__
    shape, -limit, limit, dtype, seed=self.seed)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/random_ops.py", line 240, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_random_ops.py", line 473, in _random_uniform
    name=name)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home1/grayson/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096]
	 [[Node: fc6/biases/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@fc6/biases"], dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc6/biases/Initializer/random_uniform/shape)]]
```
Anyone has an idea about it?

**Comment by kratzert** [comment]
This looks like you have not enough GPU memory available? How much do you have? On Linux you can check this out by typing `nvidia-smi` in a terminal

**Comment by graysonliu** [comment]
I don't think that's the problem. The GPU on my PC is just GTX 950M. But it's Titan X on my server. Besides, 
I don't even train the network, only testing the implement of the model, which I think doesn't need much computation power.

**Comment by kratzert** [comment]
Hmm strange, but anyway this is what the error message says. I only had this errors when I tried to use to large batch sizes, which do not fit in my GPU memory. And are you sure your GPU memory on your server is empty? Again, use `nvidia-smi` to see the actual used memory and the free memory. Maybe post a screenshot

**Comment by graysonliu** [comment]
It turns out you're right. I checked my GPU usage, a friend who shared this server with me is training a network on it,  taking up almost all memory. Thank you very much!
