### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 4, got shape [5]

### ISSUE THREAD

**Issue by xiexie123** [kratzert/finetune_alexnet_with_tensorflow#30]
hi, thanks for your sharing.
I am using your code to finetune alexnet to classify images into blur or clear. When I run finetune.py with my 'train.txt' and 'val.txt', after dozens of train_batches, I get this error :-1: tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 4, got shape [5]
         [[Node: unstack_1 = Unpack[T=DT_INT32, axis=0, num=4](Shape_3)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,227,227,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

I use python3.4, TF1.4.0

**Comment by xiexie123** [comment]
2017-11-13 19:16:56.410650: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input shape axis 0 must equal 4, got shape [5]
	 [[Node: unstack_1 = Unpack[T=DT_INT32, axis=0, num=4](Shape_3)]]
2017-11-13 19:16:01.495708 Start training...
2017-11-13 19:16:01.495774 Open Tensorboard at --logdir /root/tf12env/finetune_alexnet_with_tensorflow/tensorboard
2017-11-13 19:16:01.495788 Epoch number: 1
Traceback (most recent call last):
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 4, got shape [5]
	 [[Node: unstack_1 = Unpack[T=DT_INT32, axis=0, num=4](Shape_3)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,227,227,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./finetune.py", line 179, in <module>
    img_batch, label_batch = sess.run(next_batch)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/root/tf12env/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input shape axis 0 must equal 4, got shape [5]
	 [[Node: unstack_1 = Unpack[T=DT_INT32, axis=0, num=4](Shape_3)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,227,227,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by kratzert** [comment]
Please try again with a TF version between 1.12rc and 1.3. Seems like there are some major changes in the last 1.4 version that also brake the TensorBoard code of this example.

**Comment by xiexie123** [comment]
I try with TF1.3, still have this error....

**Comment by kratzert** [comment]
Could you also try with TF 1.2? #26 worked with TF < 1.3 maybe it's something related.

**Comment by xiexie123** [comment]
It seems the tensorborad is ok, but this error still occurs....even with TF1.2....so so weird

**Comment by kratzert** [comment]
well okay I was mainly concerned about the error not tensorboard. Strange, error though. 

My biggest guess is, that one path (to an image) in your textfile is not correct. To verify this, you could write a small script that does nothing more than loading all your images from the path in your text file and e.g. just calculate the mean or something. I once had similar problems and finally figured out that there some images in my folder with a space in the name. But since the my ImageDataGenerator class splits each line in the text file by spaces, this resulted in errors.

Even faster: just use the `os` library and `os.isfile` and iterate over the items in datagenerator.img_paths and check if each element in this list is a valid file.

**Comment by xiexie123** [comment]
ok I will check all the images. thanks for you kind help

**Comment by xiexie123** [comment]
hi，I checked all the images and find nothing.
but, FYI. I changed you code:
img_decoded = tf.image.decode_png(img_string, channels=3) ->img_decoded = tf.image.decode_image(img_string, channels=3)
and add:
 img_data_jpg = tf.image.convert_image_dtype(img_decoded, dtype=tf.float32)
to corp image:
img_resized = tf.image.resize_image_with_crop_or_pad(img_data_jpg, 227, 227)

becuase when I use  tf.image.decode_png ,there is an error:
W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Got 25 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
         [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8](ReadFile)]]

and all my trained images are .jpg

**Comment by xiexie123** [comment]
I find this
[https://github.com/tensorflow/tensorflow/issues/12414](url)

I think it something to do with this.
here is my error:
2017-11-14 13:33:05.821402: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Got 5 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
         [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8](ReadFile)]]
Traceback (most recent call last):
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got 5 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
         [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8](ReadFile)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,227,227,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./finetune.py", line 180, in <module>
    img_batch, label_batch = sess.run(next_batch)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/root/tf12env2/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got 5 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
         [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8](ReadFile)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,227,227,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by xiexie123** [comment]
promble saved by add 
data = data.ignore_errors()

-_-||  still have no idea about what errors in my trainning data....

**Comment by kratzert** [comment]
Hmm okay, strange. But as I thought it must be something with your data not with the actual code itself. But glad you found a solution that worked for you.
