### ISSUE TITLE
'utf-8' codec can't encode character '\udcc0' in position 2120: surrogates not allowed

### ISSUE THREAD

**Issue by jmren168** [kratzert/finetune_alexnet_with_tensorflow#34]
Hi 

I met this error message when executing finetune.py. (shown as follows)
Environment: Win 7, Anaconda 4.3.0 , Python 3.6.1
Do you have any ideas about what happened?

Traceback (most recent call last):

  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2898, in run_code
    self.showtraceback()

  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1826, in showtraceback
    self._showtraceback(etype, value, stb)

  File "C:\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 554, in _showtraceback
    dh.parent_header, ident=topic)

  File "C:\Anaconda3\lib\site-packages\jupyter_client\session.py", line 712, in send
    to_send = self.serialize(msg, ident)

  File "C:\Anaconda3\lib\site-packages\jupyter_client\session.py", line 607, in serialize
    content = self.pack(content)

  File "C:\Anaconda3\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,

  File "C:\Anaconda3\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8')

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc0' in position 2120: surrogates not allowed

**Comment by kratzert** [comment]
Just a quick google search told me the same you could have found. Seems like you are having problems in some parts with incorrect characters in strings.  See e.g. [Stackoverflow](https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s). Anyway this isn't a problem of the code in this repository, so I'll close this issue here and you should maybe head over to SO to search for an answer.

**Comment by jmren168** [comment]
I checked the path to train: it should not include a ' mark in the start of the path as well as the end of the path. Thanks for the help.
