### ISSUE TITLE
Error finetuning

### ISSUE THREAD

**Issue by fabien-colpaert** [kratzert/finetune_alexnet_with_tensorflow#43]
Hello,

Thanks for the share. I successfully installed and validated it with Imagenet pictures.
I also created the train.txt en val.txt files.
But when I'm trying to finetune AlexNet, I get the following error : 

```
`WARNING:tensorflow:From`

 C:/Users/Fabien/PycharmProjects/finetune_alexnet_with_tensorflow/finetune.py:98: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

2018-04-01 20:11:34.920700: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-04-01 20:11:36.529273 Start training...
2018-04-01 20:11:36.529273 Open Tensorboard at --logdir /tmp/finetune_alexnet/tensorboard
2018-04-01 20:11:36.529273 Epoch number: 1
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Fabien/PycharmProjects/finetune_alexnet_with_tensorflow/finetune.py", line 175, in <module>
    keep_prob: dropout_rate})
  File "C:\Users\Fabien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\Fabien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1109, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\Users\Fabien\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: b'C:\\Users\\Fabien\\PycharmProjects\\finetune_alexnet_with_tensorflow\\flowers_train\\class13\\image_1026.jpg'
```

And I can't find out where this come from and how to solve it
Thanks for helping me :)

**Comment by kratzert** [comment]
Hey there,

you mind telling me your tensorflow version. I guess it's not the root of this problem but interesting nevertheless because of the deprecated warning at the top.

Regarding your error: It is hard to say but it seems to be a problem with your .txt files. Seems like your path to the img file is not in the correct position/order, because the program tries to convert your string to a number, which is only done for the label.

Can you maybe post the first few lines of your txt files here. Is the specific img file the first in your text file or somewhere in the middle? There might be just a mistake in this specific line?

**Comment by fabien-colpaert** [comment]
Hello,

Yes I think it was a tensorflow version problem. I finnaly was able to finetune it with my set of pictures.
Got a score of 0.6, even changing the learning_rate. But that's probably due to the bad quality of my pictures and the fact that they are not segmentized.
Now I'm trying to classify a new picture in the same way we did with the validation on some Imagnet, but I can't figure out how to find and set the new weights replacing the pretrained weights.

Can you give me some hints ? 

Thanks a lot :)

**Comment by kratzert** [comment]
This has been discussed so many times here in the issue section. Just use the search function. Closed issues are your friend

For the lazy one: [Link](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/38#issuecomment-365066342)

**Comment by Prem95** [comment]
Hi, I am still facing the issue as above mentioned by @fabien-colpaert. Here is the error that is printed out:

`ValueError: could not convert string to float: b'/Users/prem/Desktop/Palm_Seed/2018-04 25/AlexNet_Files_Images/Images-2018-04-12/PS_img_2018_03_07/Class7/7_391.jpg'`

This is the path to the training images:

`/Users/prem/Desktop/Palm_Seed/2018-04-25/AlexNet_Files_Images/Images-2018-04-12/PS_img_2018_03_07/Class0/0_245.jpg 0`


My tensorflow version is 1.8. Any help is appreciated. @kratzert
