### ISSUE TITLE
ValueError: Variable relative_positions_keys/embeddings_table already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

### ISSUE THREAD

**Issue by Rainbow1273** [kratzert/finetune_alexnet_with_tensorflow#87]
Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/SASRec5/train.py", line 67, in <module>
    model.summary()
  File "C:\Users\wx\PycharmProjects\SASRec5\model.py", line 162, in summary
    outputs=self.call([seq_inputs, pos_inputs, neg_inputs, gru_neg_inputs, gru_pos_inputs])).summary()
  File "C:\Users\wx\PycharmProjects\SASRec5\model.py", line 111, in call
    att_outputs = block([att_outputs, mask])  # (None, seq_len, dim)
  File "C:\Users\wx\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\base_layer_v1.py", line 765, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\wx\PycharmProjects\SASRec5\modules.py:193 call  *
        att_out = self.mha(x, x, x, mask)  # （None, seq_len, d_model)
    C:\Users\wx\PycharmProjects\SASRec5\modules.py:135 call  *
        relations_keys = _generate_relative_positions_matrix_embeddings(q1, k1, "relative_positions_keys")
    C:\Users\wx\PycharmProjects\SASRec5\modules.py:47 _generate_relative_positions_matrix_embeddings  *
        embeddings_table = tf.get_variable("embeddings_table", [vocab_size, depth])
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\variable_scope.py:1579 get_variable  **
        return get_variable_scope().get_variable(
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\variable_scope.py:1322 get_variable
        return var_store.get_variable(
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\variable_scope.py:576 get_variable
        return custom_getter(**custom_getter_kwargs)
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:2147 distributed_getter
        return getter(*args, **kwargs)
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\variable_scope.py:531 _true_getter
        return self._get_single_variable(
    C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\variable_scope.py:894 _get_single_variable
        raise ValueError("%s Originally defined at:\n\n%s" %

    ValueError: Variable relative_positions_keys/embeddings_table already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:
    
      File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
        self._traceback = tf_stack.extract_stack_for_node(self._c_op)
      File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py", line 3561, in _create_op_internal
        ret = Operation(
      File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
      File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 1202, in var_handle_op
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
      File "C:\Users\wx\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 162, in _variable_handle_from_shape_and_dtype
        handle = gen_resource_variable_ops.var_handle_op(
    

Process finished with exit code 1

**Comment by Rainbow1273** [comment]
I insert  tf.reset_default_graph()  but has 'AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

**Comment by kratzert** [comment]
Hey there,

this repository is > 3 years old and was developed under an old version of tensorflow. I do not maintain this code anymore but kept it for the sake of archiving it. If you are still interested in running this code, make sure to use an old version of Tensorflow (I  think >= 1.2.0 but < 2.0)
