### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by wang7393** [kratzert/finetune_alexnet_with_tensorflow#9]
I run my own dataset,it apper the fllowing error,why?\

Traceback (most recent call last):
  File "finetune.py", line 109, in <module>
    horizontal_flip = True, shuffle = True)
  File "/mnt/data/wxb/finetune_alexnet_with_tensorflow/datagenerator.py", line 33, in __init__
    self.shuffle_data()
  File "/mnt/data/wxb/finetune_alexnet_with_tensorflow/datagenerator.py", line 55, in shuffle_data
    images = self.images.copy()
AttributeError: 'list' object has no attribute 'copy

**Comment by kratzert** [comment]
It's because you are using Python 2. This code base is written for the use with Python 3
